### ISSUE TITLE
Couldn't load file or assembly 'dnlib

### ISSUE THREAD

**Issue by malthaelix** [SychicBoy/NETReactorSlayer#56]
Hello, when I run the cli (latest release), I am getting the exception below. (Same as well for GUI when I click to "Start Deobfuscation" button)

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'dnlib, Version=3.6.0.0, Culture=neutral, PublicKeyToken=50e96378b6e77999' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NETReactorSlayer.Core.Stages.ControlFlowDeobfuscator..ctor()
   at NETReactorSlayer.Core.Options..ctor(IReadOnlyList`1 args) in D:\a\NETReactorSlayer\NETReactorSlayer\NETReactorSlayer.Core\Options.cs:line 215
   at NETReactorSlayer.Core.Program.Main(String[] args) in D:\a\NETReactorSlayer\NETReactorSlayer\NETReactorSlayer.Core\Program.cs:line 41
   at NETReactorSlayer.CLI.Program.Main(String[] args) in D:\a\NETReactorSlayer\NETReactorSlayer\NETReactorSlayer.CLI\Program.cs:line 22
```

I am not sure if there is a problem in my end but I doubt. Any help appreciated.

**Comment by SychicBoy** [comment]
Hi, did you build it yourself or did you just download the binaries from the releases page?

**Comment by malthaelix** [comment]
I downloaded from releases page, yes.

**Comment by SychicBoy** [comment]
I'm not sure what caused it, you can join to the discord server and ask for help:
https://discord.gg/nPJ9zTCMYr
